import json, sys, datetime
M = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "detector_model.json"))
def arr(v): return "new float[] { " + ", ".join(f"{float(x):.9g}f" for x in v) + " }"
sizes = [len(M["mean"])] + [len(b) for b in M["b"]]
lines = []
lines.append("// <auto-generated>")
lines.append("// Generated by tools/damage-model/gen_model_cs.py from detector_model.json. Do not edit by hand -")
lines.append("// retrain with tools/damage-model/train.py and regenerate instead.")
lines.append(f"// Features ({len(M['names'])}): {', '.join(M['names'])}")
lines.append("// </auto-generated>")
lines.append("namespace PicRestore.Restoration.DamageDetection;\n")
lines.append("internal static class LearnedDamageModel\n{")
lines.append(f"    public const float Threshold = {M['threshold']}f;\n")
lines.append(f"    public const int SmoothRadius = {M['smooth']};\n")
lines.append(f"    public const int TrainingPairCount = {len(M.get('pairs', [])) or 1};\n")
lines.append(f"    public static readonly int[] LayerSizes = {{ {', '.join(map(str, sizes))} }};\n")
lines.append(f"    public static readonly float[] FeatureMean = {arr(M['mean'])};\n")
lines.append(f"    public static readonly float[] FeatureScale = {arr(M['scale'])};\n")
lines.append("    public static readonly float[][] Weights =\n    {")
for W in M["W"]:
    flat = [x for row in W for x in row]
    lines.append(f"        {arr(flat)},")
lines.append("    };\n")
lines.append("    public static readonly float[][] Biases =\n    {")
for b in M["b"]:
    lines.append(f"        {arr(b)},")
lines.append("    };")
lines.append("}")
open(sys.argv[2] if len(sys.argv) > 2 else "LearnedDamageModel.g.cs", "w").write("\n".join(lines) + "\n")
print("sizes", sizes)
